name=input("Enter the boy name")
programming_language=input("Enter the programming language")
mentor=input("Enter the mentor Name")
print("\n Here is my little story based on mad libs game")
print(f"once upon a time there was a boy named {name}")
print(f"{name} was very curios and always want to learn new thing ")
print(f"One day he decided to learn {programming_language} at the PIAIC")
print(f"Lucikiley  {name} found a great mentor name as {mentor} who was expert in {programming_language}")
print("And so his Journey Continues......")